### ISSUE TITLE
Angular 9 Ivy support (Failed to compile entry-point @angular-material-extensions/password-strength)

### ISSUE THREAD

**Issue by orlovskyalex** [angular-material-extensions/password-strength#270]
### Bug Report or Feature Request (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
```

### OS and Version?

macOS Catalina 10.15.3

### Versions

```sh
Angular CLI: 9.0.1
Node: 10.16.0
OS: darwin x64

Angular: 9.0.0
... animations, cdk, common, compiler, compiler-cli, core, forms
... language-service, material, material-moment-adapter
... platform-browser, platform-browser-dynamic, router
Ivy Workspace: Yes

Package                           Version
-----------------------------------------------------------
@angular-devkit/architect         0.900.1
@angular-devkit/build-angular     0.900.1
@angular-devkit/build-optimizer   0.900.1
@angular-devkit/build-webpack     0.900.1
@angular-devkit/core              9.0.1
@angular-devkit/schematics        9.0.1
@angular/cli                      9.0.1
@angular/flex-layout              9.0.0-beta.29
@ngtools/webpack                  9.0.1
@schematics/angular               9.0.1
@schematics/update                0.900.1
rxjs                              6.5.3
typescript                        3.7.5
webpack                           4.41.2
```

### Repro steps

1. `npx @angular/cli new compile-ivy --minimal --interactive false --routing false --skipTests`
1. `cd compile-ivy`
1. `ng add @angular/material` (any theme, Yes to all the questions)
1. `ng add @angular-material-extensions/password-strength`
1. `./node_modules/.bin/ngcc --properties es2015 browser module main --first-only --create-ivy-entry-points` (from [Angular's guide](https://angular.io/guide/ivy#speeding-up-ngcc-compilation))

### The log given by the failure

```sh
Compiling @angular-material-extensions/password-strength : es2015 as esm2015
Error: Error on worker #1: Error: Failed to compile entry-point @angular-material-extensions/password-strength (es2015 as esm2015) due to compilation errors:
node_modules/@angular-material-extensions/password-strength/esm2015/password-strength.js:668:26 - error NG1010: Value at position 1 in the NgModule.imports of MatPasswordStrengthModule is not a reference: [object Object]

668                 imports: [
                             ~
669                     CommonModule,
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
... 
673                     MatRippleModule
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
674                 ],
    ~~~~~~~~~~~~~~~~~

    at ClusterWorker.compile (/Users/orlovsky/www/compile-ivy/node_modules/@angular/compiler-cli/ngcc/src/main.js:177:27)
    at Worker.<anonymous> (/Users/orlovsky/www/compile-ivy/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/worker.js:44:42)
    at Worker.emit (events.js:198:13)
    at process.Worker.process.on (internal/cluster/worker.js:28:12)
    at process.emit (events.js:198:13)
    at emit (internal/child_process.js:832:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at ClusterMaster.onWorkerMessage (/Users/orlovsky/www/compile-ivy/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:158:27)
    at /Users/orlovsky/www/compile-ivy/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:46:95
    at ClusterMaster.<anonymous> (/Users/orlovsky/www/compile-ivy/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:238:57)
    at step (/Users/orlovsky/www/compile-ivy/node_modules/tslib/tslib.js:136:27)
    at Object.next (/Users/orlovsky/www/compile-ivy/node_modules/tslib/tslib.js:117:57)
    at /Users/orlovsky/www/compile-ivy/node_modules/tslib/tslib.js:110:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/orlovsky/www/compile-ivy/node_modules/tslib/tslib.js:106:16)
    at EventEmitter.<anonymous> (/Users/orlovsky/www/compile-ivy/node_modules/@angular/compiler-cli/ngcc/src/execution/cluster/master.js:232:32)
    at EventEmitter.emit (events.js:198:13)
```

### Desired functionality

I want it to be compiled successfully so that I can start the project

### Mention any other details that might be useful

–

**Comment by AnthonyNahas** [comment]
in the next few days, I will publsih major release that's supporting ivy🍻

**Comment by AnthonyNahas** [comment]
duplicate #240

**Comment by turnono** [comment]
This issue is still happening
